title: Stuff from my time at Sandia National Laboratories
theme: jekyll-theme-minimal
description: Sensitivity Analysis for the Component Design App; Manufacturing Controls Methods for High-Consequence, Single-Use Systems
